[versions]
ksp = "2.0.0-1.0.23"
kotlinJupyter = "0.12.0-139"

ktlint = "12.1.1"

# make sure to sync manually with :generator module
kotlin = "2.0.0"
kotlinpoet = "1.16.0"
dokka = "1.9.10"

libsPublisher = "1.8.10-dev-43"

# "Bootstrap" version of the dataframe, used in the build itself to generate @DataSchema APIs,
# dogfood Gradle / KSP plugins in tests and idea-examples modules
dataframe = "0.13.1"

# TODO 0.1.6 breaks kotlinter (which is no longer in use), https://github.com/Kotlin/dataframe/issues/598
korro = "0.1.5"

# TODO Requires more work to be updated to 0.7.0+
# https://github.com/Kotlin/dataframe/issues/594
kover = "0.6.1"

commonsCsv = "1.10.0"
commonsCompress = "1.26.0"
commonsIo = "2.16.1"
serialization = "1.7.0"
fuel = "2.3.1"
poi = "5.2.5"
mariadb = "3.3.2"
h2db = "2.3.230"
mssql = "12.6.3.jre11"
mysql = "9.0.0"
postgresql = "42.7.3"
sqlite = "3.45.3.0"
jtsCore = "1.18.1"
kotlinDatetime = "0.6.0"
openapi = "2.1.20"
kotlinLogging = "7.0.0"
sl4j = "2.0.12"

junit = "4.13.2"
junit-jupiter = "5.10.2"
junit-platform = "1.10.2"

# TODO 5.8.0 is not possible due to https://github.com/Kotlin/dataframe/issues/595
kotestAsserions = "5.5.4"

jsoup = "1.17.2"
arrow = "17.0.0"
docProcessor = "0.3.10"
simpleGit = "2.0.3"
dependencyVersions = "0.51.0"
plugin-publish = "1.2.1"
shadow = "8.1.1"
android-gradle-api = "7.3.1" # Can't be updated to 7.4.0+ due to Java 8 compatibility
ktor-server-netty = "2.3.8"
kotlin-compile-testing = "1.6.0"
duckdb = "0.10.0"
buildconfig = "5.4.0"

[libraries]
ksp-gradle = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
jupyter-api = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-kernel", version.ref = "kotlinJupyter" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-scriptingJvm = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-jvm", version.ref = "kotlin" }
commonsCsv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commonsCsv" }
commonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
# Serialization
serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

fuel = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
h2db = { group = "com.h2database", name = "h2", version.ref = "h2db" }
mssql = { group = "com.microsoft.sqlserver", name = "mssql-jdbc", version.ref = "mssql" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
jts = { group = "org.locationtech.jts", name = "jts-core", version.ref = "jtsCore" }

poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
kotlin-datetimeJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime-jvm", version.ref = "kotlinDatetime" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-commons = { group = "org.junit.platform", name = "junit-platform-commons", version.ref = "junit-platform" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-runner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junit-platform" }
junit-platform-suite-api = { group = "org.junit.platform", name = "junit-platform-suite-api", version.ref = "junit-platform" }

kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotestAsserions" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

arrow-format = { group = "org.apache.arrow", name = "arrow-format", version.ref = "arrow" }
arrow-vector = { group = "org.apache.arrow", name = "arrow-vector", version.ref = "arrow" }
arrow-memory = { group = "org.apache.arrow", name = "arrow-memory-unsafe", version.ref = "arrow" }
arrow-c-data = { group = "org.apache.arrow", name = "arrow-c-data", version.ref = "arrow" }


kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
swagger = { group = "io.swagger.parser.v3", name = "swagger-parser", version.ref = "openapi" }

kotlinLogging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlinLogging" }
sl4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "sl4j" }
android-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "android-gradle-api" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-api" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor-server-netty" }
kotlin-compile-testing = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing", version.ref = "kotlin-compile-testing" }
kotlin-compile-testing-ksp = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version.ref = "kotlin-compile-testing" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "kotlin" }
kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-compiler-internal-test-framework = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-internal-test-framework", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
kotlin-annotations-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-annotations-jvm", version.ref = "kotlin" }
kotlin-jupyter-test-kit = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-test-kit", version.ref = "kotlinJupyter" }

dataframe-symbol-processor = { group = "org.jetbrains.kotlinx.dataframe", name = "symbol-processor-all" }

duckdb-jdbc = { group = "org.duckdb", name = "duckdb_jdbc", version.ref= "duckdb"}

[plugins]
jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlinJupyter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
keywordGenerator = { id = "org.jetbrains.dataframe.generator", version = "1.0" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "libsPublisher" }
korro = { id = "io.github.devcrocod.korro", version.ref = "korro" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dataframe = { id = "org.jetbrains.kotlinx.dataframe", version.ref = "dataframe" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
docProcessor = { id = "nl.jolanrensen.docProcessor", version.ref = "docProcessor" }
simpleGit = { id = "xyz.ronella.simple-git", version.ref = "simpleGit" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dependencyVersions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
